foodplan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls', namespace='recipes'))
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('trial_recip_page/', views.trial_recip_page, name='trial_recip_page' )
]

accounts/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models


class Recipes(models.Model):
    PUBLICATION_CHOICES = (
            ('Published', 'Опубликовано'),
            ('archived', 'В архиве'),
        )
    title = models.CharField(max_length=200, verbose_name='Название рецепта')
    description = models.TextField(blank=True, verbose_name="Описание рецепта")
    ingredients = models.ManyToManyField('Ingredient', verbose_name="Ингредиенты")
    image = models.ImageField(upload_to='media/recipes/img', verbose_name="Картинка с рецептом")
    publication = models.CharField(max_length=20, choices=PUBLICATION_CHOICES, default='archived', verbose_name="Опубликовано")

    class Meta:
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название ингредиента')
    calories = models.PositiveIntegerField(blank=True, null=True, verbose_name="Калории")

    class Meta:
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0, blank=True, null=True)

    class Meta:
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"

accounts/views.py
from django.shortcuts import render

# Create your views here.

recipes/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html' )


def trial_recip_page(request):
    return render(request, 'trial_recip_page.html')

templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Подписка</button>
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form>
                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp">
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="exampleInputPassword1" class="form-label">Пароль</label>
                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                            </div>
                            <input type="password" class="form-control" id="password">
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit"
                                    class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="#" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Войти</button>
            </div>
        </nav>
    </header>
    {% block content %}{% endblock %}
    <footer class="footer py-4 mt-5" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-between mb-2">
            <a href="https://vk.com/devmanorg">
                <img src="{% static 'img/vk.png' %}" height="40" width="auto" alt="">
            </a>
            <div>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Виды меню</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Блог</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Контакты</b></a>
            </div>
        </div>
        <div class="container">
            <h6 class="link-secondary text-center"><a href="#" class="link-secondary me-2">Политика конфиденциальности</a><a href="#" class="link-secondary">Пользовательское соглашение</a></h6>
            <h6 class="link-secondary text-center">© Devman 2022. All right reserved.</h6>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/card3.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Назад</button>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="img/circle1.png" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
                        <div class="row">
                            <h2>Название рецепта</h2>
                            <div class="col-12 col-sm-6">
                                <h6>Рецепт рецепт Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non.</h6>
                            </div>
                            <div class="col-12 col-sm-6">
                                <small class="link-secondary">Ингредиенты:</small>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                </ul>
                                <small class="link-secondary">Общая калорийность: 1000 ккал</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Главная{% endblock %}
{% block content %}
    <main style="margin-top: calc(2rem + 85px);">
        <section class="foodplan__head_bg">
            <div class="container">
                <div class="d-flex w-50 py-lg-5 foodplan__head">
                    <div class="d-flex flex-column justify-content-start foodplan__head_desc">
                        <h1 class="mb-5"><b>Вдохновляем готовить дома!</b></h1>
                        <h4>Мы планируем домашнее меню.<br>
                            Вы получаете рецепты + список продуктов.<br>
                            Больше не нужно думать, что готовить.</h4>
                        <div class="d-block mt-3">
                            <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Хочу попробовать</button>
                            <a href="{% url 'recipes:trial_recip_page' %}"
                               class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Пробный рецепт</a>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="container my-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static 'img/circle1.png' %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title"><b>Меню на неделю</b></h5>
                                <p class="card-text">Итальянская паста, котлеты с пюре или овощное карри - решать вам!
                                Подстраивайте меню под свои желания.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static 'img/circle2.png' %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title"><b>Удобный список продуктов</b></h5>
                                <p class="card-text">С четким списком вы не возьмете лишнего, будете тратить меньше и сможете чаще покупать лосось и морепродукты.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                        <div class="card mb-1 foodplan__card_borderless">
                            <img src="{% static 'img/circle3.png' %}" class="card-img-top" alt="">
                            <div class="card-body">
                                <h5 class="card-title"><b>Доставка от ВкусВилл</b></h5>
                                <p class="card-text">Заказывайте доставку продуктов по вашему списку в 1 клик. Все ингредиенты попадут в корзину ВкусВилл автоматически.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="container my-5">
                <h1 class="text-center my-4"><b>В каждом меню только хиты</b></h1>
                <div class="container w-md-75">
                    <div id="carousel1" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="...">
                                <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                    <h5><b>Модный и полезный ужин</b></h5>
                                    <h2><b>Боул с креветками и рисом</b></h2>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="...">
                                <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                    <h5><b>Интересно, просто и супер вкусно</b></h5>
                                    <h2><b>Тосканский суп с фаршем</b></h2>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="...">
                                <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                    <h5><b>Понятное всей семье, яркое на вкус</b></h5>
                                    <h2><b>Паприкаш с курицей</b></h2>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="{% static 'img/4.jpg' %}" class="d-block w-100" alt="...">
                                <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                    <h5></h5><b>Летнее удовольствие</b></h5>
                                    <h2><b>Овощной салат с жареным халуми</b></h2>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="https://foodplan.ru/local/images-for-pages/landing/img/cards/5.jpg" class="d-block w-100"
                                    alt="...">
                                <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                    <h5><b>Который все пекут повторно</b></h5>
                                    <h2><b>Брауни чизкейк с ягодами</b></h2>
                                </div>
                            </div>
                        </div>
                        <button class="carousel-control-prev carousel__button_prev" type="button" data-bs-target="#carousel1"
                            data-bs-slide="prev">
                            <span class="foodplan_green" aria-hidden="true">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-left-circle carousel__svg_prev"
                                    viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                                </svg>
                            </span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next carousel__button_next" type="button" data-bs-target="#carousel1"
                            data-bs-slide="next">
                            <span class="foodplan_green" aria-hidden="true">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-circle carousel__svg_next"
                                    viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                        d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
                                </svg>
                            </span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
                
            </div>
        </section>
        <section>
            <div class="container mb-5">
                <h1 class="mb-3 text-center"><strong>Истории наших пользователей</strong></h1>
                <div class="row">
                    <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                        <img src="{% static 'img/IMG_1899.jpg' %}" alt="" class="foodplan__story">
                    </div>
                    <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                        <img src="{% static 'img/IMG_1900.jpg' %}" alt="" class="foodplan__story">
                    </div>
                    <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                        <img src="{% static 'img/IMG_1901.jpg' %}" alt="" class="foodplan__story">
                    </div>
                    <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                        <img src="{% static 'img/IMG_1902.jpg' %}" alt="" class="foodplan__story">
                    </div>
                </div>
            </div>
        </section>
        <section>
            <div class="container mb-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="d-flex flex-row justify-content-between m-1">
                            <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                            <div class="d-flex flex-column align-items-center text-center justify-content-center">
                                <h5>Выпускник Сбербанк 500 Startups</h5>
                                <h5>Moscow</h5>
                            </div>
                            <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="d-flex flex-row justify-content-between m-1">
                            <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                            <div class="d-flex flex-column align-items-center text-center justify-content-center">
                                <h5>Диплом повара Le Cordon Bleu</h5>
                                <h5>London</h5>
                            </div>
                            <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="d-flex flex-row justify-content-between m-1">
                            <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                            <div class="d-flex flex-column align-items-center text-center justify-content-center">
                                <h5>При поддержке Austrian Angel Investors</h5>
                                <h5>Vienna</h5>
                            </div>
                            <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/trial_recip_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}Главная{% endblock %}
{% block content %}
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="{% static img/circle1.png" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
                        <div class="row">
                            <h2>Название рецепта</h2>
                            <div class="col-12 col-sm-6">
                                <h6>Рецепт рецепт Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi eius nemo voluptatum minus
                                    facilis blanditiis ut architecto rem maiores, aperiam aut debitis repellat quod voluptates natus, laboriosam hic
                                    adipisci non.</h6>
                            </div>
                            <div class="col-12 col-sm-6">
                                <small class="link-secondary">Ингредиенты:</small>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                    <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                </ul>
                                <small class="link-secondary">Общая калорийность: 1000 ккал</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}